version: '3'

volumes:
  vendor: {}
  redis_data: {}
  npm: {}
  postgres_data: {}

services:
  app: &laravel
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - '.:/app:delegated'
      - '~/.ssh:/root/.ssh:delegated'
      - 'vendor:/app/vendor'
      - 'npm:/app/node_modules'
    depends_on:
      - db
      - redis

  frontend:
    <<: *laravel
    container_name: frontend
    command: npm run dev
    ports:
      - "5173:5173"

  db:
    image: postgres:16.4
    container_name: gw-db
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: psswd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    # container_name: redis
    image: redis:alpine
    container_name: gw-redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s


  # docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token
  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared
  #   command: tunnel --no-autoupdate run
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     TUNNEL_HOSTNAME: chandelier.juantrejo.cloud
  #     TUNNEL_URL: http://app:8000
  #     TUNNEL_TOKEN: ${TUNNEL_TOKEN}
  #     REDSI_URL: redis://redis:6379
  #     TUNNEL_LOGLEVEL: debug
  #   depends_on:
  #     - redis
    # volumes:
    #   - ~/.cloudflared:/root/.cloudflared

  # etl:
  #   <<: *laravel
  #   container_name: etl
  #   command: php artisan etl:run
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - '.:/app:delegated'
  #     - 'vendor:/app/vendor'
  #     - 'npm:/app/node_modules'
